#!/bin/bash
#SBATCH --time=48:00:00
#SBATCH --job-name=fairai_t
#SBATCH --cpus-per-task=60
#SBATCH --partition=gpu
#SBATCH --gpus-per-node 1
#SBATCH --mail-type=ALL
#SBATCH --mem=240G
#SBATCH --mail-user=ashutiwa@iu.edu



which python;

# srun snakemake -R --until generate_node_embeddings  -call --config gnn_model=gat env=local device=cuda:0 r2v=true crosswalk=true dataset=pokec  --nolock --ignore-incomplete;
# srun snakemake -R --until generate_node_embeddings  -call --config gnn_model=gcn env=local device=cuda:0 r2v=true crosswalk=true dataset=pokec  --nolock --ignore-incomplete;
# srun snakemake -R --until generate_node_embeddings  -call --config gnn_model=gat env=local device=cuda:0 r2v=false crosswalk=true dataset=pokec  --nolock --ignore-incomplete;
# srun snakemake -R --until generate_node_embeddings  -call --config gnn_model=gcn env=local device=cuda:0 r2v=false crosswalk=true dataset=pokec  --nolock --ignore-incomplete;
cd /N/slate/ashutiwa/big_red/residual2vec_temp
pwd;
srun snakemake -R --until generate_node_embeddings  -call --config gnn_model=gat env=local device=cuda:0 r2v=true crosswalk=false dataset=pokec  --nolock --ignore-incomplete;
srun snakemake -R --until generate_node_embeddings  -call --config gnn_model=gcn env=local device=cuda:0 r2v=true crosswalk=false dataset=pokec  --nolock --ignore-incomplete;
srun snakemake -R --until generate_node_embeddings  -call --config gnn_model=gat env=local device=cuda:0 r2v=false crosswalk=false dataset=pokec  --nolock --ignore-incomplete;
srun snakemake -R --until generate_node_embeddings  -call --config gnn_model=gcn env=local device=cuda:0 r2v=false crosswalk=false dataset=pokec  --nolock --ignore-incomplete;
